name: Run DB Migration

on:
  push:
    branches:
      - full-stack

jobs:
  migrate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Run migration
        run: npm run migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}